---
title: "Diamonds"
author: "Jakob Liebmann"
date: "8 April 2020"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show  
    theme: united
    highlight: tango
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# Loading the diamonds dataset

```{r}
library(tidyverse)
library(skimr)
df <- ggplot2::diamonds
skim(df)
head(df)
#help(diamonds)
```

# Visual exploration
## Amounts
```{r}

#funktionsorientierter Ansatz funktioniert leider nicht! :-(
#===========================================================
# jplot<-function(j=){
#   pic<-df%>%
#     group_by(j)%>%
#     summarise(amount=n())%>%
#     ggplot(aes(j, amount))+
#     geom_col()
#   return(pic)
# }
# jplot("cut")
#===========================================================

#some visualisation-work
df%>%
  group_by(cut)%>%
  summarise(amount=n())%>%
  ggplot(aes(cut, amount))+
  geom_col()

df%>%
  group_by(color)%>%
  summarise(amount=n())%>%
  ggplot(aes(color, amount))+
  geom_col()

df%>%
  group_by(clarity)%>%
  summarise(amount=n())%>%
  ggplot()+
  geom_col(aes(clarity, amount))

# generating the same result with geom_bar()
df%>%
  group_by(clarity)%>%
  ggplot()+
  geom_bar(aes(x=clarity))

# turning into horizontal
df%>%
  group_by(cut)%>%
  summarise(amount=n())%>%
  ggplot(aes(amount, cut))+           #option 1: switching aesthetics
  geom_col()

df%>%
  group_by(color)%>%
  summarise(amount=n())%>%
  ggplot(aes(color, amount))+
  geom_col()+
  coord_flip()                        #option 2: flipping coordinates

#reordering by counts

df%>%
  count(clarity)%>%
  ggplot(aes(y=n, x=fct_reorder(clarity, -n)))+    #descending
  geom_col()+
  labs(x="clarity", y="amount")

df%>%
  count(clarity)%>%
  ggplot(aes(y=n, x=fct_reorder(clarity, n)))+     #ascending
  geom_col()+
  labs(x="clarity", y="amount")
```

## Amounts by 2 categories

```{r}
df%>%
  ggplot(aes(cut, color))+
  geom_count()

df%>%
  ggplot(aes(clarity, color))+
  geom_jitter()

df%>%
  ggplot(aes(cut, clarity))+
  geom_hex()

df%>%
  ggplot(aes(color, cut))+
  geom_point(aes(color=color), position = "jitter")

df%>%
  count(color, clarity)%>%
  ggplot(aes(color, clarity, fill=n))+
  geom_tile()
```

## Distributions

```{r}
df%>%
  ggplot()+
  geom_histogram(aes(price), bins=10)

df%>%
  ggplot(aes(carat))+
  geom_histogram(aes(y=stat(density)))

#to be honest....built complete nonsense here ;-)
df%>%
  ggplot(aes(carat, price, color=cut, shape=clarity))+
  geom_point()+
  geom_density2d(colour = "red", size = 0.5, n = 15)+
  theme_bw()

df%>%
  ggplot(aes(color, carat))+
  geom_boxplot()
```






